//API 1
GET http://localhost:3000/todos/?status=TO%20DO
###

GET http://localhost:3000/todos/?priority=HIGH
###

GET http://localhost:3000/todos/?priority=HIGH&status=IN%20PROGRESS
###

GET http://localhost:3000/todos/?search_q=Buy
###

GET http://localhost:3000/todos/?category=WORK&status=DONE
###

GET http://localhost:3000/todos/?category=HOME
###

GET http://localhost:3000/todos/?category=LEARNING&priority=HIGH
###

//API 2

GET http://localhost:3000/todos/1/
###

//API 3
GET http://localhost:3000/agenda/?date=2021-12-12
###

//API 4
POST http://localhost:3000/todos/
{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
Content-Type:application/json
###

//API 5

PUT http://localhost:3000/todos/:todoId/
{
  "status": "DONE"
}
Content-Type: application/json
###

PUT http://localhost:3000/todos/:todoId/
{
  "priority": "HIGH"
}
Content-Type: application/json
###

PUT http://localhost:3000/todos/:todoId/
{
  "todo": "Clean the garden"
}
Content-Type: application/json
###

PUT http://localhost:3000/todos/:todoId/
{
  "category": "LEARNING"
}
Content-Type: application/json
##
PUT http://localhost:3000/todos/:todoId/
{
  "dueDate": "2021-01-12"
}
Content-Type: application/json
###

//API 6

DELETE http://localhost:3000/todos/:todoId/
###
